### ISSUE TITLE
VM clone halts

### ISSUE THREAD

**Issue by timtrace** [33hops/xsibackup#2]
Greetings, I enjoy xsibackup very much. Thank you.

I have encountered a problem. One of my VMs clones to 58% then xsibackup unceremoniously jumps to the next VM.  Here's a pastebin, we're most interested in line 47: http://pastebin.com/J4TRqbGi

There exists plenty of disk space for the operation.

Why might this be happening?

**Comment by 33hops** [comment]
Are you sure the disk is not being fully backed up? and that the issue is not just just an effect of the progress info not being updated properly. Another user reported the same problem but I have not been able to reproduce the matter so far. Sorry for the delay but the discussion group at http://sourceforge.net/p/xsibackup/discussion/?source=navbar is the main hub by now.

**Comment by timtrace** [comment]
I'll move the conversation over there :)
